-- Sprint 19 — MVP insight rules (groups A–E)
INSERT INTO insight_rules (
  rule_code,
  rule_group,
  name,
  severity,
  priority_weight,
  condition_type,
  condition_config,
  title_template,
  body_template,
  kpi_code_filter
)
VALUES
  (
    'A_BELOW_PEER_SCRAP',
    'A',
    'Scrap rate below peer median',
    'critical',
    3,
    'below_peer_median',
    '{"min_gap": 0}'::jsonb,
    'Scrap above peers on {{line_code}}',
    '{{line_code}}: scrap rate {{current_value}} is below the cohort median (gap {{gap_signed}}). Closing the gap to peer p50 could reduce material loss.',
    'SCRAP_RATE'
  ),
  (
    'A_BELOW_PEER_OEE',
    'A',
    'OEE below peer median',
    'critical',
    2.8,
    'below_peer_median',
    '{}'::jsonb,
    'OEE lags peers — {{line_code}}',
    '{{line_code}}: OEE {{current_value}} trails the peer median (gap {{gap_signed}}). Review availability, performance, and quality losses.',
    'OEE'
  ),
  (
    'B_BELOW_TARGET',
    'B',
    'KPI below factory target',
    'warning',
    2.2,
    'below_target',
    '{}'::jsonb,
    'Below target: {{kpi_code}} ({{line_code}})',
    '{{line_code}} {{kpi_name}} is {{current_value}} vs factory target {{target_value}} (gap {{gap_signed}}).',
    NULL
  ),
  (
    'B_BELOW_TARGET_SCRAP',
    'B',
    'Scrap above factory target',
    'critical',
    2.5,
    'below_target',
    '{}'::jsonb,
    'Scrap exceeds factory target — {{line_code}}',
    'Scrap rate {{current_value}} on {{line_code}} is above the factory target {{target_value}}.',
    'SCRAP_RATE'
  ),
  (
    'C_VALIDATION_ERROR',
    'C',
    'Data validation error',
    'critical',
    3.5,
    'validation_error',
    '{}'::jsonb,
    'Fix data error on {{line_code}}',
    '{{issue_message}} ({{issue_code}}) on line {{line_code}} blocks reliable KPI and benchmark results.',
    NULL
  ),
  (
    'C_VALIDATION_WARNING',
    'C',
    'Data validation warning',
    'warning',
    1.2,
    'validation_warning',
    '{}'::jsonb,
    'Data warning — {{line_code}}',
    '{{issue_message}} on {{line_code}}. Review before month-end close.',
    NULL
  ),
  (
    'D_LOW_PERCENTILE',
    'D',
    'Tier-1 KPI in bottom quartile',
    'warning',
    2,
    'low_percentile',
    '{"max_percentile": 25, "tier": 1}'::jsonb,
    'Bottom quartile: {{kpi_code}} ({{line_code}})',
    '{{kpi_code}} on {{line_code}} is around the {{percentile}}th percentile vs peers (value {{current_value}}).',
    NULL
  ),
  (
    'D_INSUFFICIENT_PEERS',
    'D',
    'Insufficient peer sample',
    'info',
    0.8,
    'insufficient_peer_sample',
    '{}'::jsonb,
    'Benchmark sample too small — {{kpi_code}}',
    'Only {{peer_sample_size}} peer factories in cohort for {{kpi_code}} on {{line_code}}. Interpret gaps cautiously.',
    NULL
  ),
  (
    'E_ENERGY_GAP',
    'E',
    'Energy per kg above peers',
    'warning',
    1.8,
    'below_peer_median',
    '{}'::jsonb,
    'Energy intensity gap — {{line_code}}',
    '{{line_code}}: energy per kg {{current_value}} is worse than peer median (gap {{gap_signed}}).',
    'ENERGY_PER_KG'
  ),
  (
    'E_COST_GAP',
    'E',
    'Cost per kg above peers',
    'warning',
    1.7,
    'below_peer_median',
    '{}'::jsonb,
    'Unit cost gap — {{line_code}}',
    '{{line_code}}: cost per kg {{current_value}} is above peer median (gap {{gap_signed}}).',
    'COST_PER_KG'
  ),
  (
    'E_DOWNTIME_GAP',
    'E',
    'Downtime ratio above peers',
    'warning',
    1.6,
    'below_peer_median',
    '{}'::jsonb,
    'Downtime vs peers — {{line_code}}',
    'Downtime ratio {{current_value}} on {{line_code}} is worse than cohort median.',
    'DOWNTIME_RATIO'
  ),
  (
    'E_YIELD_GAP',
    'E',
    'Yield below peer median',
    'warning',
    1.9,
    'below_peer_median',
    '{}'::jsonb,
    'Yield opportunity — {{line_code}}',
    'Yield {{current_value}} on {{line_code}} is below peer median (gap {{gap_signed}}).',
    'YIELD_RATE'
  ),
  (
    'A_GAP_OEE_COMPONENT',
    'A',
    'Availability drag on OEE',
    'info',
    1.3,
    'below_peer_median',
    '{}'::jsonb,
    'Availability below peers — {{line_code}}',
    'Availability {{current_value}} on {{line_code}} is under peer median; check planned and unplanned stops.',
    'AVAILABILITY'
  ),
  (
    'B_OEE_BELOW_TARGET',
    'B',
    'OEE below factory target',
    'critical',
    2.6,
    'below_target',
    '{}'::jsonb,
    'OEE below target — {{line_code}}',
    'OEE {{current_value}} on {{line_code}} is below factory target {{target_value}}.',
    'OEE'
  );
